
import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { content, inputType } = await req.json()
    const apiKey = Deno.env.get('GEMINI_API_KEY')

    if (!apiKey) {
      return new Response(
        JSON.stringify({ error: 'Gemini API key not configured' }),
        { 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 500 
        }
      )
    }

    let prompt = ''
    if (inputType === 'url') {
      prompt = `Please rewrite and enhance the content from this URL into a comprehensive blog post. Make it engaging, well-structured, and SEO-friendly. URL: ${content}`
    } else {
      prompt = `Please rewrite and enhance this text into a comprehensive, engaging blog post. Make it well-structured, professional, and SEO-friendly. Original text: ${content}`
    }

    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 2048,
        }
      })
    })

    if (!response.ok) {
      throw new Error(`Gemini API error: ${response.status}`)
    }

    const data = await response.json()
    const rewrittenContent = data.candidates?.[0]?.content?.parts?.[0]?.text

    if (!rewrittenContent) {
      throw new Error('No content generated by Gemini API')
    }

    // Generate a title from the content
    const lines = rewrittenContent.split('\n').filter(line => line.trim())
    const title = lines[0]?.replace(/^#+\s*/, '') || 'AI Generated Article'

    return new Response(
      JSON.stringify({
        success: true,
        title,
        content: rewrittenContent
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (error) {
    console.error('Gemini rewrite error:', error)
    return new Response(
      JSON.stringify({ error: 'Failed to rewrite content with AI' }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500 
      }
    )
  }
})
