// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byhsuhveohkmvhphvpvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5aHN1aHZlb2hrbXZocGh2cHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyOTUwMDcsImV4cCI6MjA2NTg3MTAwN30.JATwVxxIDJ_3m23FmzxSTVUKTqg286czHqM0Qb3nLhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);